@startuml Cognito-reset-password

title AWS Cognito\nパスワードリセット

actor "管理、一般ユーザー(Browser)"

"管理、一般ユーザー(Browser)" -> WebApp

WebApp -> "Cognito user pool" : パスワードリセット

"Cognito user pool" -> SES

SES -> "管理、一般ユーザー(Browser)" : 認証コードの送信

note left: email

WebApp -> "Cognito user pool" : 認証コード、新パスワード確認

"Cognito user pool" -> WebApp

WebApp -> "Cognito user pool" : 新パスワードで認証

"Cognito user pool" -> WebApp

@enduml